### ISSUE TITLE
Revision

### ISSUE THREAD

**Issue by yoancmaes** [yosbel-penate/avangenio_auth_text#1]
Porque dos material  app anidadas ?

https://github.com/yosbel-penate/avangenio_auth_app/blob/7fffa34461574c4776b36f0d179bbc3354476dfc/lib/main.dart#L36

**Comment by yoancmaes** [comment]
Poque no usas el mecanismo de material para validar ??

https://github.com/yosbel-penate/avangenio_auth_app/blob/7fffa34461574c4776b36f0d179bbc3354476dfc/lib/tools/custom_widget/email_text_field.dart#L30C12-L34C60

**Comment by yoancmaes** [comment]
Porque no usas un formulario aqui ? 

https://github.com/yosbel-penate/avangenio_auth_app/blob/7fffa34461574c4776b36f0d179bbc3354476dfc/lib/screens/login_screen.dart#L23C12-L23C21

**Comment by yosbel-penate** [comment]
Definitivamente, tienes razón, lo arreglaré

**Comment by yosbel-penate** [comment]
ok
